# Generated by Django 4.2.1 on 2025-07-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FashionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('designer_name', models.CharField(max_length=100)),
                ('designer_contact', models.CharField(blank=True, help_text='Optional: Email, social media handle, or website.', max_length=255)),
                ('image', models.ImageField(upload_to='fashion_gallery/')),
                ('category', models.CharField(choices=[('men', "Men's Fashion"), ('women', "Women's Fashion"), ('patterns', 'Patterns & Textiles'), ('avant-garde', 'Avant-Garde')], default='women', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
