# Generated by Django 4.2.1 on 2025-09-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fashionitem',
            name='image',
        ),
        migrations.AddField(
            model_name='fashionitem',
            name='media_file',
            field=models.FileField(default='', help_text='Upload an image (jpg, png, etc.) or a video (mp4, mov, etc.)', upload_to='fashion_gallery/'),
            preserve_default=False,
        ),
    ]
